using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace gishadev.tools.Core
{
#if UNITY_EDITOR
    public static class CodeGenerator
    {
        private const string GeneratedDirectory = "Assets/_Project/Scripts/Generated/";

        // Enum name -> the typed overload it unlocks ({0} is the enum name). An entry is only
        // emitted when its enum file exists, so a project with no PoolDataSO doesn't end up with
        // pool overloads referencing enums that were never generated.
        private static readonly (string EnumName, string Method)[] TypedOverloads =
        {
            (Constants.AUDIO_MUSIC_ENUM_NAME,
                "public static void PlayMusic(this IAudioManager @this, {0} music) => @this.PlayMusic((int)music);"),
            (Constants.AUDIO_SFX_ENUM_NAME,
                "public static void PlaySFX(this IAudioManager @this, {0} sfx) => @this.PlaySFX((int)sfx);"),
            (Constants.POOL_SFX_ENUM_NAME,
                "public static GameObject EmitAt(this ISFXEmitter @this, {0} sfx, Vector3 position, Quaternion? rotation = null) => @this.EmitAt((int)sfx, position, rotation);"),
            (Constants.POOL_VFX_ENUM_NAME,
                "public static GameObject EmitAt(this IVFXEmitter @this, {0} vfx, Vector3 position, Quaternion? rotation = null) => @this.EmitAt((int)vfx, position, rotation);"),
            (Constants.POOL_OTHER_ENUM_NAME,
                "public static GameObject EmitAt(this IOtherEmitter @this, {0} other, Vector3 position, Quaternion? rotation = null) => @this.EmitAt((int)other, position, rotation);"),
            (Constants.POOL_OTHER_ENUM_NAME,
                "public static GameObject GetPrefab(this IOtherEmitter @this, {0} other) => @this.GetPrefab((int)other);"),
        };

        public static void GenerateEnumClass(string enumName, string[] enumEntries)
        {
            string path = GeneratedDirectory + enumName + ".cs";

            var str = new StringBuilder();
            str.AppendFormat("public enum {0}", enumName);
            str.AppendLine();
            str.AppendLine("{");

            for (var i = 0; i < enumEntries.Length; i++)
            {
                str.AppendFormat("\t{0}", ValidateEnumString(enumEntries[i]));

                if (i < enumEntries.Length - 1)
                {
                    str.Append(',');
                    str.AppendLine();
                }
            }

            str.AppendLine();
            str.AppendLine(@"}");

            FileInfo file = new FileInfo(path);
            file.Directory?.Create();

            File.WriteAllText(path, str.ToString());
            AssetDatabase.ImportAsset(path);
        }

        // Regenerated alongside the enums, so it can never drift out of sync with them.
        // If it ever does go stale against a package update, delete it and hit GENERATE ENUMS -
        // nothing else depends on it, the int-based IAudioManager/emitter methods always work.
        public static void GenerateExtensionsClass()
        {
            string path = GeneratedDirectory + "GeneratedExtensionMethods.cs";

            var str = new StringBuilder();
            str.AppendLine("// Auto-generated by gishadev.tools - do not edit.");
            str.AppendLine("// Regenerate with the GENERATE ENUMS button on AudioMasterSO / PoolDataSO.");
            str.AppendLine("using gishadev.tools.Audio;");
            str.AppendLine("using gishadev.tools.Effects;");
            str.AppendLine("using UnityEngine;");
            str.AppendLine();
            str.AppendLine("public static class GeneratedExtensionMethods");
            str.AppendLine("{");

            foreach (var (enumName, method) in TypedOverloads)
            {
                if (!File.Exists(GeneratedDirectory + enumName + ".cs"))
                    continue;

                str.Append("    ");
                str.AppendLine(string.Format(method, enumName));
            }

            str.AppendLine("}");

            FileInfo file = new FileInfo(path);
            file.Directory?.Create();

            File.WriteAllText(path, str.ToString());
            AssetDatabase.ImportAsset(path);
        }

        private static string ValidateEnumString(string text)
        {
            if (text.Length <= 0)
            {
                Debug.LogError("Invalid enum name");
                return null;
            }

            // Turn all whitespaces into _.
            string whitespacePattern = @"\s+";
            string replacement = "_";
            var result = Regex.Replace(text, whitespacePattern, replacement).ToUpper();

            // First char must be a letter or an underscore.
            string specialCharactersPattern = @"[^\w\d]+";
            result = Regex.Replace(result, specialCharactersPattern, "_");

            return result;
        }
    }
#endif
}
